export const ObservabilityEvent = Object.freeze({
  AOE_DECISION_REQUESTED: "AOE_DECISION_REQUESTED",
  AOE_DECISION_IDEMPOTENT_HIT: "AOE_DECISION_IDEMPOTENT_HIT",
  AOE_DECISION_COMPLETED: "AOE_DECISION_COMPLETED",
  AOE_DECISION_FAILED: "AOE_DECISION_FAILED",
  AOE_CATALOG_LOAD_FAILED: "AOE_CATALOG_LOAD_FAILED",
  AOE_HUMAN_REVIEW_CREATED: "AOE_HUMAN_REVIEW_CREATED",
  AOE_HUMAN_REVIEW_COMPLETED: "AOE_HUMAN_REVIEW_COMPLETED",
  AOE_AUTHORIZATION_DENIED: "AOE_AUTHORIZATION_DENIED",
  AOE_INVALID_REQUEST: "AOE_INVALID_REQUEST",
  AOE_SERVICE_HEALTH_CHECK: "AOE_SERVICE_HEALTH_CHECK",
});
