-- MANUAL_FIRST_CUTOVER_ONLY
-- STEP 01 WORKOUT DELIVERY POSTCHECK
-- READ_ONLY_SQL=YES
select 'PASS_SKIP_STOP:workout_table_exists' as check_name, to_regclass('public.treino_eventos') as current_state;
select 'PASS_SKIP_STOP:workout_columns' as check_name, table_name, column_name, data_type, is_nullable, column_default from information_schema.columns where table_schema = 'public' and table_name in ('treinos', 'treino_eventos') and column_name in ('lifecycle_status','template_origin_id','template_origin_type','template_origin_name','template_origin_snapshot','applied_by','applied_at','delivered_by','delivered_at','completed_at','archived_at','data_fim','data_revisao','application_idempotency_key','id','treino_id','user_id','aluno_id','event_type','from_status','to_status','actor_id','metadata','occurred_at','created_at') order by table_name, column_name;
select 'PASS_SKIP_STOP:workout_constraints' as check_name, conrelid::regclass::text as table_name, conname, pg_get_constraintdef(oid) as definition from pg_constraint where connamespace = 'public'::regnamespace and conname in ('treinos_lifecycle_status_check','treinos_lifecycle_dates_check','treinos_template_origin_type_check','treinos_template_origin_snapshot_object_check','treino_eventos_pkey','treino_eventos_treino_id_fkey','treino_eventos_aluno_id_fkey','treino_eventos_event_type_check','treino_eventos_metadata_object_check') order by conname;
select 'PASS_SKIP_STOP:workout_indexes' as check_name, indexname, indexdef from pg_indexes where schemaname = 'public' and indexname in ('treinos_user_aluno_lifecycle_idx','treinos_user_delivered_at_idx','treinos_user_template_origin_idx','treinos_user_application_idempotency_uidx','treino_eventos_user_treino_occurred_idx','treino_eventos_user_aluno_occurred_idx','treino_eventos_treino_event_type_idx') order by indexname;
select 'PASS_SKIP_STOP:workout_rpc_hashes' as check_name, p.proname, md5(pg_get_functiondef(p.oid)) as body_hash_target, p.prosecdef, pg_get_functiondef(p.oid) like '%SET search_path TO public%' as search_path_public from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname in ('salvar_treino_composto','entregar_treino','alterar_estado_treino') order by p.proname;
select 'PASS_SKIP_STOP:workout_rls' as check_name, relname, relrowsecurity from pg_class where relnamespace = 'public'::regnamespace and relname = 'treino_eventos';
select 'PASS_SKIP_STOP:workout_policies' as check_name, tablename, policyname, roles, cmd, qual from pg_policies where schemaname = 'public' and tablename = 'treino_eventos';
select 'PASS_SKIP_STOP:workout_grants_delegated_to_phase1' as check_name, grantee, privilege_type from information_schema.table_privileges where table_schema = 'public' and table_name = 'treino_eventos';
