import { useCallback, useEffect, useMemo, useState } from "react";
import { Calculator, RefreshCw } from "lucide-react";
import { listSmartManagementLocations, listSmartManagementServices } from "../../../services/smartManagementService";
import { calculateProfitability } from "../utils/profitabilityEngine";
import { formatServicePrice } from "../utils/servicesPricing";
import { formatMoney, ruleSummary } from "../utils/transferRules";

export default function ProfitabilityOverview({ onNavigate }) {
  const [services, setServices] = useState([]); const [locations, setLocations] = useState([]);
  const [serviceId, setServiceId] = useState(""); const [locationId, setLocationId] = useState(""); const [studentCount, setStudentCount] = useState("");
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [nextServices, nextLocations] = await Promise.all([listSmartManagementServices("active"), listSmartManagementLocations("active")]); setServices(nextServices); setLocations(nextLocations); } catch { setError("Não foi possível carregar os cadastros para a estimativa."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const service = services.find((item) => item.id === serviceId) || null;
  const location = locations.find((item) => item.id === locationId) || null;
  const result = useMemo(() => service && location && studentCount !== "" ? calculateProfitability({ service, location, studentCount: Number(studentCount) }) : null, [service, location, studentCount]);
  if (loading) return <div className="smart-management-state" role="status">Carregando dados para a estimativa...</div>;
  if (error) return <div className="smart-management-state smart-management-error" role="alert"><span>{error}</span><button type="button" className="btn btn-secondary" onClick={load}><RefreshCw size={16} aria-hidden="true" />Tentar novamente</button></div>;
  if (!services.length) return <Empty title="Cadastre um serviço para calcular uma estimativa." action="Ir para Serviços & Precificação" onAction={() => onNavigate("services")} />;
  if (!locations.length) return <Empty title="Cadastre e configure um local para calcular uma estimativa." action="Ir para Locais & Repasses" onAction={() => onNavigate("locations")} />;
  return <section className="smart-management-profitability" aria-labelledby="profitability-overview-title"><div className="smart-management-simulator-toolbar"><div><h2 id="profitability-overview-title">Rentabilidade</h2><p>Estimativa por atendimento com base nos cadastros ativos.</p></div></div><div className="smart-management-profitability-form"><label>Serviço<select value={serviceId} onChange={(event) => { setServiceId(event.target.value); setStudentCount(""); }}><option value="">Selecione</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name} - {formatServicePrice(item)}</option>)}</select></label><label>Local<select value={locationId} onChange={(event) => setLocationId(event.target.value)}><option value="">Selecione</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name} - {ruleSummary(item.rule)}</option>)}</select></label><label>Quantidade de alunos considerada<input type="number" inputMode="numeric" min={service?.minStudents || 1} max={service?.maxStudents || undefined} step="1" value={studentCount} onChange={(event) => setStudentCount(event.target.value)} /></label></div>{!result && <p className="smart-management-profitability-note" role="status">Selecione um serviço, um local e a quantidade de alunos para ver a estimativa.</p>}{result && !result.valid && <div className="smart-management-profitability-invalid" role="alert"><strong>Configuração inválida</strong><span>{result.errors[0]?.message}</span></div>}{result?.valid && <Result result={result} />}</section>;
}

function Empty({ title, action, onAction }) { return <section className="smart-management-empty-state"><Calculator size={30} aria-hidden="true" /><h2>{title}</h2><button type="button" className="btn btn-primary" onClick={onAction}>{action}</button></section>; }
function Result({ result }) { const metrics = [["Receita da sessão", result.grossRevenue], ["Repasse", result.transferAmount], ["Receita após repasse", result.netAfterTransfer], ...(result.netHourlyRate === null ? [] : [["Valor por hora", result.netHourlyRate, true]])]; return <div className="smart-management-profitability-result" aria-live="polite"><div className="smart-management-profitability-metrics">{metrics.map(([label, value, hourly]) => <div className={`smart-management-profitability-metric ${value < 0 ? "is-negative" : ""}`} key={label}><span>{label}</span><strong>{formatMoney(value / 100)}{hourly ? "/h" : ""}</strong></div>)}</div>{result.netAfterTransfer < 0 && <p className="smart-management-profitability-note">Receita após repasse negativa.</p>}<section className="smart-management-breakdown"><h3>Como o resultado foi calculado</h3><ol>{result.breakdown.map((item) => <li key={item.key}><strong>{item.label}</strong><b>{formatMoney(item.value / 100)}{item.key === "hourly" ? "/h" : ""}</b></li>)}</ol></section><p className="smart-management-profitability-note">Valores estimados pelas regras cadastradas. Não representam receita recebida.</p></div>; }
