create index if not exists perfis_user_id_idx on public.perfis using btree (user_id);
create index if not exists perfis_tipo_acesso_idx on public.perfis using btree (tipo_acesso);
create index if not exists perfis_status_idx on public.perfis using btree (status);
create index if not exists alunos_user_vencimento_idx on public.alunos using btree (user_id, vencimento);
create index if not exists alunos_user_acompanhamento_status_idx on public.alunos using btree (user_id, acompanhamento_status);
create unique index if not exists alunos_student_user_id_uidx on public.alunos using btree (student_user_id) where student_user_id is not null;
create index if not exists alunos_student_user_id_idx on public.alunos using btree (student_user_id) where student_user_id is not null;
create index if not exists planos_user_id_idx on public.planos using btree (user_id);
create index if not exists planos_ativo_idx on public.planos using btree (ativo);
create index if not exists planos_user_ativo_idx on public.planos using btree (user_id, ativo);
create unique index if not exists planos_user_nome_normalizado_unique_idx on public.planos using btree (user_id, lower(regexp_replace(btrim(nome), '\s+'::text, ' '::text, 'g'::text)));
create index if not exists assinaturas_user_id_idx on public.assinaturas using btree (user_id);
create index if not exists assinaturas_status_idx on public.assinaturas using btree (status);
create index if not exists assinaturas_data_vencimento_idx on public.assinaturas using btree (data_vencimento);
create index if not exists assinaturas_user_created_at_idx on public.assinaturas using btree (user_id, created_at desc);
create index if not exists assinaturas_user_status_vencimento_idx on public.assinaturas using btree (user_id, status, data_vencimento);
create index if not exists pagamentos_user_id_idx on public.pagamentos using btree (user_id);
create index if not exists pagamentos_aluno_id_idx on public.pagamentos using btree (aluno_id);
create index if not exists pagamentos_data_pagamento_idx on public.pagamentos using btree (data_pagamento);
create index if not exists pagamentos_user_aluno_data_idx on public.pagamentos using btree (user_id, aluno_id, data_pagamento desc, created_at desc);
create index if not exists admin_logs_admin_user_id_idx on public.admin_logs using btree (admin_user_id);
create index if not exists admin_logs_target_user_id_idx on public.admin_logs using btree (target_user_id);
create index if not exists admin_logs_acao_idx on public.admin_logs using btree (acao);
create index if not exists admin_logs_created_at_idx on public.admin_logs using btree (created_at desc);
create index if not exists aceites_legais_user_id_idx on public.aceites_legais using btree (user_id);
create index if not exists aceites_legais_versoes_idx on public.aceites_legais using btree (politica_versao, termos_versao);
create index if not exists aceites_legais_aceito_em_idx on public.aceites_legais using btree (aceito_em);
create index if not exists avaliacoes_user_id_idx on public.avaliacoes using btree (user_id);
create index if not exists avaliacoes_aluno_id_idx on public.avaliacoes using btree (aluno_id);
create index if not exists avaliacoes_data_idx on public.avaliacoes using btree (data_avaliacao);
create index if not exists avaliacoes_user_data_idx on public.avaliacoes using btree (user_id, data_avaliacao desc);
create index if not exists anamneses_user_id_idx on public.anamneses using btree (user_id);
create index if not exists anamneses_aluno_id_idx on public.anamneses using btree (aluno_id);
create index if not exists anamneses_user_created_at_idx on public.anamneses using btree (user_id, created_at desc);
create index if not exists treinos_user_id_idx on public.treinos using btree (user_id);
create index if not exists treinos_aluno_id_idx on public.treinos using btree (aluno_id);
create index if not exists treinos_user_created_at_idx on public.treinos using btree (user_id, created_at desc);
create index if not exists treinos_user_aluno_lifecycle_idx on public.treinos using btree (user_id, aluno_id, lifecycle_status);
create index if not exists treinos_user_delivered_at_idx on public.treinos using btree (user_id, delivered_at desc);
create index if not exists treinos_user_template_origin_idx on public.treinos using btree (user_id, template_origin_type, template_origin_id);
create unique index if not exists treinos_user_application_idempotency_uidx on public.treinos using btree (user_id, application_idempotency_key) where application_idempotency_key is not null;
create index if not exists treino_dias_treino_id_idx on public.treino_dias using btree (treino_id);
create index if not exists treino_exercicios_treino_dia_id_idx on public.treino_exercicios using btree (treino_dia_id);
create index if not exists treino_exercicios_exercise_id_idx on public.treino_exercicios using btree (exercise_id) where exercise_id is not null;
create index if not exists exercise_library_origin_status_name_idx on public.exercise_library using btree (origin, status, name);
create index if not exists exercise_library_owner_status_name_idx on public.exercise_library using btree (owner_id, status, name) where owner_id is not null;
create index if not exists exercise_library_muscle_category_idx on public.exercise_library using btree (muscle_group, category) where status = 'active';
create index if not exists exercise_favorites_professional_idx on public.exercise_favorites using btree (professional_id, created_at desc);
create index if not exists treino_eventos_user_treino_occurred_idx on public.treino_eventos using btree (user_id, treino_id, occurred_at desc);
create index if not exists treino_eventos_user_aluno_occurred_idx on public.treino_eventos using btree (user_id, aluno_id, occurred_at desc);
create index if not exists treino_eventos_treino_event_type_idx on public.treino_eventos using btree (treino_id, event_type);
create index if not exists acompanhamento_eventos_user_id_idx on public.acompanhamento_eventos using btree (user_id);
create index if not exists acompanhamento_eventos_aluno_id_idx on public.acompanhamento_eventos using btree (aluno_id);
create index if not exists acompanhamento_eventos_ocorrido_em_idx on public.acompanhamento_eventos using btree (ocorrido_em desc);
create index if not exists acompanhamento_eventos_user_aluno_ocorrido_idx on public.acompanhamento_eventos using btree (user_id, aluno_id, ocorrido_em desc);
create unique index if not exists acompanhamento_eventos_user_event_key_uidx on public.acompanhamento_eventos using btree (user_id, event_key) where event_key is not null;
create index if not exists workout_templates_owner_id_idx on public.workout_templates using btree (owner_id);
create index if not exists workout_templates_owner_updated_idx on public.workout_templates using btree (owner_id, updated_at desc);
create index if not exists workout_templates_owner_split_idx on public.workout_templates using btree (owner_id, split_type);
create unique index if not exists aoe_idempotency_unique_key on public.aoe_idempotency_keys using btree (coalesce(organization_id, '00000000-0000-0000-0000-000000000000'::uuid), actor_id, operation, idempotency_key);
create unique index if not exists aoe_human_reviews_one_active_per_decision on public.aoe_human_reviews using btree (decision_id);
create index if not exists aoe_decisions_request_idx on public.aoe_decisions using btree (request_id);
create index if not exists aoe_decisions_student_idx on public.aoe_decisions using btree (student_id);
create index if not exists aoe_decisions_actor_idx on public.aoe_decisions using btree (actor_id);
create index if not exists aoe_decisions_org_idx on public.aoe_decisions using btree (organization_id);
create index if not exists aoe_decisions_model_idx on public.aoe_decisions using btree (selected_model_code);
create index if not exists aoe_traces_decision_idx on public.aoe_decision_traces using btree (decision_id);
create index if not exists aoe_reviews_decision_idx on public.aoe_human_reviews using btree (decision_id);
create index if not exists aoe_idempotency_expires_idx on public.aoe_idempotency_keys using btree (expires_at);
create index if not exists aoe_audit_org_event_date_idx on public.aoe_audit_events using btree (organization_id, event_type, occurred_at desc);
