export const Sex = Object.freeze({ MALE: "MALE", FEMALE: "FEMALE", OTHER: "OTHER", NOT_INFORMED: "NOT_INFORMED" });
export const ExperienceLevel = Object.freeze({ BEGINNER: "BEGINNER", INTERMEDIATE: "INTERMEDIATE", ADVANCED: "ADVANCED", UNKNOWN: "UNKNOWN" });
export const Goal = Object.freeze({ HYPERTROPHY: "HYPERTROPHY", WEIGHT_LOSS: "WEIGHT_LOSS", STRENGTH: "STRENGTH", HEALTH: "HEALTH", REHABILITATION: "REHABILITATION", CONDITIONING: "CONDITIONING" });
export const TrainingSplit = Object.freeze({ ABC: "ABC", ABCD: "ABCD", ABCDE: "ABCDE", FULL_BODY: "FULL_BODY", UPPER_LOWER: "UPPER_LOWER" });
export const Strategy = Object.freeze({ BASE: "BASE", PERFORMANCE: "PERFORMANCE", EFFICIENCY: "EFFICIENCY", SPECIALIZATION: "SPECIALIZATION" });
export const EquipmentProfile = Object.freeze({ FULL_GYM: "FULL_GYM", LIMITED_GYM: "LIMITED_GYM", HOME_BASIC: "HOME_BASIC", BODYWEIGHT_ONLY: "BODYWEIGHT_ONLY", CUSTOM: "CUSTOM" });
export const RuleOutcome = Object.freeze({ PASS: "PASS", FAIL: "FAIL", WARNING: "WARNING", NOT_APPLICABLE: "NOT_APPLICABLE" });
export const RecommendationStatus = Object.freeze({ RECOMMENDED: "RECOMMENDED", RECOMMENDED_WITH_WARNINGS: "RECOMMENDED_WITH_WARNINGS", HUMAN_REVIEW_REQUIRED: "HUMAN_REVIEW_REQUIRED", NO_ELIGIBLE_MODEL: "NO_ELIGIBLE_MODEL", ADDITIONAL_DATA_REQUIRED: "ADDITIONAL_DATA_REQUIRED", CATALOG_UNAVAILABLE: "CATALOG_UNAVAILABLE", INVALID_INPUT: "INVALID_INPUT" });
export const ConfidenceLevel = Object.freeze({ HIGH: "HIGH", MEDIUM: "MEDIUM", LOW: "LOW" });
export const HumanReviewStatus = Object.freeze({ NOT_REQUIRED: "NOT_REQUIRED", REQUIRED: "REQUIRED", APPROVED: "APPROVED", APPROVED_WITH_ADJUSTMENTS: "APPROVED_WITH_ADJUSTMENTS", REJECTED: "REJECTED", ADDITIONAL_INFORMATION_REQUIRED: "ADDITIONAL_INFORMATION_REQUIRED" });

export const ReasonCodes = Object.freeze({
  GOAL_MISMATCH: "GOAL_MISMATCH",
  LEVEL_TOO_LOW: "LEVEL_TOO_LOW",
  LEVEL_MISMATCH: "LEVEL_MISMATCH",
  FREQUENCY_INSUFFICIENT: "FREQUENCY_INSUFFICIENT",
  DURATION_INSUFFICIENT: "DURATION_INSUFFICIENT",
  EQUIPMENT_MISSING: "EQUIPMENT_MISSING",
  MODEL_NOT_HOMOLOGATED: "MODEL_NOT_HOMOLOGATED",
  MODEL_RELEASE_INACTIVE: "MODEL_RELEASE_INACTIVE",
  RECOVERY_INSUFFICIENT: "RECOVERY_INSUFFICIENT",
  SPECIALIZATION_PREREQUISITE_MISSING: "SPECIALIZATION_PREREQUISITE_MISSING",
  ADHERENCE_RISK: "ADHERENCE_RISK",
  CRITICAL_CONSTRAINT: "CRITICAL_CONSTRAINT",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  MISSING_DATA: "MISSING_DATA",
  TIE_UNRESOLVED: "TIE_UNRESOLVED",
  HUMAN_REVIEW_REQUIRED: "HUMAN_REVIEW_REQUIRED",
  CATALOG_INVALID: "CATALOG_INVALID",
  SELECTED_MODEL_MISSING: "SELECTED_MODEL_MISSING",
  INVALID_SCORE: "INVALID_SCORE",
  DECISION_TRACE_INCOMPLETE: "DECISION_TRACE_INCOMPLETE",
  VERSION_REGISTRY_INCOMPLETE: "VERSION_REGISTRY_INCOMPLETE",
  SELECTION_RANKING_MISMATCH: "SELECTION_RANKING_MISMATCH",
  TIME_AT_LIMIT: "TIME_AT_LIMIT",
  RECOVERY_AT_LIMIT: "RECOVERY_AT_LIMIT",
  EQUIPMENT_ADAPTATION_REQUIRED: "EQUIPMENT_ADAPTATION_REQUIRED",
  PREFERENCE_MISMATCH: "PREFERENCE_MISMATCH",
  MULTIPLE_WARNINGS: "MULTIPLE_WARNINGS",
  SPECIALIZATION_PARTIAL_READINESS: "SPECIALIZATION_PARTIAL_READINESS",
});
