const card = {
  background: "white",
  padding: "20px",
  borderRadius: "8px",
  boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
};

const styles = {
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))",
    gap: "20px",
    marginTop: "25px",
  },
  conteudo: {
    padding: "24px",
    marginLeft: "260px",
    width: "calc(100% - 260px)",
  },
  card,
  numeroCard: {
    fontSize: "24px",
    fontWeight: "700",
    marginTop: "10px",
  },
  cardDescricao: {
    fontSize: "13px",
    lineHeight: 1.45,
    margin: "8px 0 0",
  },
  filtrosCard: {
    ...card,
    marginTop: "30px",
  },
  secaoTitulo: {
    margin: 0,
    fontSize: "22px",
  },
  secaoLegenda: {
    color: "#6b7280",
    fontSize: "14px",
    marginTop: "6px",
  },
  secaoAjuda: {
    fontSize: "13px",
    lineHeight: 1.45,
    margin: "6px 0 0",
    maxWidth: "760px",
  },
  filtros: {
    display: "grid",
    gridTemplateColumns:
      "minmax(220px, 1fr) minmax(170px, 220px) minmax(180px, 220px) auto",
    gap: "10px",
    marginTop: "18px",
  },
  segmentedControl: {
    display: "inline-flex",
    flexWrap: "wrap",
    gap: "6px",
    marginTop: "16px",
  },
  segmentedButton: {
    background: "#f3f4f6",
    border: "1px solid #d1d5db",
    borderRadius: "999px",
    color: "#374151",
    cursor: "pointer",
    fontWeight: "800",
    minHeight: "36px",
    padding: "8px 12px",
  },
  segmentedButtonActive: {
    background: "#111827",
    borderColor: "#111827",
    color: "white",
  },
  campoGrupo: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  labelCampo: {
    color: "#374151",
    fontSize: "13px",
    fontWeight: "700",
  },
  campo: {
    width: "100%",
    minHeight: "42px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    padding: "9px 11px",
    background: "white",
    color: "#111827",
    outline: "none",
  },
  tabela: {
    width: "100%",
    borderCollapse: "collapse",
    background: "#fff",
    borderRadius: "8px",
    overflow: "hidden",
  },
  linhaCabecalho: {
    background: "#111827",
    color: "#fff",
  },
  header: {
    padding: "12px",
    textAlign: "left",
  },
  celula: {
    padding: "12px",
    borderBottom: "1px solid #e5e7eb",
  },
  estadoVazio: {
    padding: "12px",
    borderBottom: "1px solid #e5e7eb",
    color: "#6b7280",
    textAlign: "center",
  },
  botaoReceber: {
    background: "#16a34a",
    color: "white",
    border: "none",
    padding: "8px 12px",
    borderRadius: "6px",
    cursor: "pointer",
  },
  botaoNeutro: {
    background: "#e5e7eb",
    color: "#111827",
    border: "none",
    padding: "8px 12px",
    borderRadius: "6px",
    cursor: "pointer",
  },
  erroBox: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "8px",
    color: "#991b1b",
    fontSize: "14px",
    fontWeight: "700",
    marginTop: "16px",
    padding: "12px",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
    background: "rgba(17, 24, 39, 0.55)",
  },
  modal: {
    maxHeight: "calc(100vh - 48px)",
    overflowY: "auto",
    background: "white",
    borderRadius: "8px",
    padding: "24px",
    boxShadow: "0 24px 70px rgba(15, 23, 42, 0.28)",
  },
  modalTopo: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    alignItems: "flex-start",
  },
  modalAcoes: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    justifyContent: "flex-end",
  },
  modalTitulo: {
    margin: 0,
    fontSize: "22px",
  },
  modalGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: "12px",
    marginTop: "20px",
  },
  rodapeModal: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "22px",
  },
  filtrosHistorico: {
    display: "grid",
    gridTemplateColumns: "minmax(180px, 240px)",
    marginTop: "18px",
  },
  tabelaModal: {
    marginTop: "18px",
  },
  mobileModalList: {
    marginTop: "18px",
  },
  resumoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "12px",
    marginTop: "20px",
  },
  resumoItem: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    display: "grid",
    gap: "6px",
    padding: "14px",
  },
  relatorioBox: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    marginTop: "18px",
    padding: "16px",
  },
  subtituloModal: {
    margin: 0,
    fontSize: "16px",
  },
  rankingGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "12px",
    marginTop: "20px",
  },
  rankingCard: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "14px",
  },
  listaCompacta: {
    display: "grid",
    gap: "8px",
    marginTop: "12px",
  },
  rankingLinha: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
    justifyContent: "space-between",
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: "8px",
  },
};

export default styles;
