export const PENALTIES = Object.freeze({
  TIME_AT_LIMIT: -3,
  RECOVERY_AT_LIMIT: -5,
  ADHERENCE_RISK: -5,
  PREFERENCE_MISMATCH: -2,
  EQUIPMENT_ADAPTATION_REQUIRED: -4,
  MULTIPLE_WARNINGS: -5,
  SPECIALIZATION_PARTIAL_READINESS: -6,
});

export const MAX_PENALTY_TOTAL = -20;
